### PR TITLE
[Auto-generated] Update dependencies

### PR DESCRIPTION
**Pull request by TEAM4-0**
### Update dependencies

Automatically created PR from [`ci/dependency-updates`](https://github.com/EMMC-ASBL/tripper/tree/ci/dependency-updates).

The PR is based on the ['CI - Update dependencies PR' workflow](https://SINTEF.github.io/ci-cd/latest/workflows/ci_update_dependencies/) in [SINTEF/ci-cd](https://github.com/SINTEF/ci-cd).

#### To do

- [ ] Check that the diff is sensible, and that tests and builds pass with the new dependency versions.
- [ ] Make sure that the PR is **squash** merged, with a sensible commit message.

### CODE REVIEW

**Comment by CasperWA** [comment]
@sygout Note that this update forces v0.4.0 for DLite, which has proven to have some issues. However, the immediate ones should be irrelevant, as this repository also depends on `pint`.

**Comment by sygout** [comment]
So does it mean that we should approve it as all the tests are working? or wait for new version of DLite without bugs?

**Comment by CasperWA** [comment]
> So does it mean that we should approve it as all the tests are working? or wait for new version of DLite without bugs?

That's quite a subjective thing, really. As the version has proven buggy, I'd probably personally prefer to avoid the specific version, i.e., add `,!=0.4.0` to the DLite dependency, and otherwise leave it as it was prior to the suggested update here.

**Comment by sygout** [comment]
ok then we go for that and exclude 0.4.0 and then I approve the merge request

**Comment by jesper-friis** [comment]
> ok then we go for that and exclude 0.4.0 and then I approve the merge request
> 
> Still I will put a comment no that in the chat Team4.0

Excluding dlite-python 0.4.0 breaks

**Pull request merged**
