### PR TITLE
Ignore vulnerability in mkdocs-material 9.2.7

### PR DESCRIPTION
**Pull request by jesper-friis**
# Description:
Ignore vulnerability in mkdocs-material 9.2.7

For details, see: https://data.safetycli.com/v/64496/97c

## Type of change:

- [ ] Bug fix and code cleanup.
- [ ] New feature.
- [ ] Documentation update.
- [x] Testing.

## Checklist for the reviewer:

This checklist should be used as a help for the reviewer.

- [ ] Is the change limited to one issue?
- [ ] Does this PR close the issue?
- [ ] Is the code easy to read and understand?
- [ ] Do all new feature have an accompanying new test?
- [ ] Has the documentation been updated as necessary?

### CODE REVIEW

**Comment by ajeklund** [comment]
I think that PR #186 (which has now been merged) is a more robust solution to the mkdocs-material vulnerability.

**Comment by jesper-friis** [comment]
Closing. Fixed in a better way in PR #186

**Comment by jesper-friis** [comment]
Reopen this one, since there seems to be some issues with #186

**Comment by jesper-friis** [comment]
PR #186 worked. Reclosing.

**Pull request closed without merging**
